import { z } from 'zod';
import { createEndpoint, Config, AshrayLevels, Services, AshrayChecklist, ZiteError } from 'zite-integrations-backend-sdk';

export default createEndpoint({
  description: 'Seeds Config, AshrayLevels, and Services tables with real data from PDF — Super Guide only',
  authenticated: true,
  inputSchema: z.object({ confirm: z.literal('SEED_REAL_DATA') }),
  outputSchema: z.object({
    deletedLevels: z.number(),
    deletedConfig: z.number(),
    deletedServices: z.number(),
    deletedChecklists: z.number(),
    levelsCreated: z.number(),
    configCreated: z.number(),
    servicesCreated: z.number(),
    status: z.string(),
  }),
  execute: async ({ input, context }) => {
    if (context.user!.role !== 'Super Guide') throw new ZiteError({ code: 'FORBIDDEN', message: 'Super Guide access required' });
    if (input.confirm !== 'SEED_REAL_DATA') throw new Error('Confirmation required');

    // Delete existing dummy data
    const [existingLevels, existingConfig, existingServices, existingChecklists] = await Promise.all([
      AshrayLevels.findAll({}),
      Config.findAll({}),
      Services.findAll({}),
      AshrayChecklist.findAll({}),
    ]);

    await Promise.all([
      ...existingLevels.records.map(r => AshrayLevels.delete({ id: r.id })),
      ...existingConfig.records.map(r => Config.delete({ id: r.id })),
      ...existingServices.records.map(r => Services.delete({ id: r.id })),
      ...existingChecklists.records.map(r => AshrayChecklist.delete({ id: r.id })),
    ]);

    // Seed AshrayLevels (from PDF pages 81-86)
    const levelsResult = await AshrayLevels.bulkCreate({
      records: [
        {
          levelName: 'Jigyasa',
          levelOrder: 1,
          courseSyllabus: 'Jigyasa',
          noGambling: false,
          noIllicitSex: false,
          avoidNonveg: false,
          kanthiMala: false,
        },
        {
          levelName: 'Shraddhavan',
          levelOrder: 2,
          chantingRoundsRequired: 1,
          chantingMonths: 3,
          morningProgram: 'none',
          spReadingPagesPerMonth: 20,
          booksToRead: 'BBD',
          courseSyllabus: 'PT',
          classFreqPerMonth: 1,
          oneOnOnePerMonth: 1,
          acceptKrishnaSpg: 'NO',
          serviceHoursMonth: 2,
          donationRequired: 'none',
          avoidOnionGarlic: 'aware',
          avoidIntoxicants: 'aware',
          noGambling: false,
          noIllicitSex: false,
          avoidNonveg: false,
          fasting: 'aware',
          kanthiMala: false,
          sadhanaScoreRequired: 'fill',
          sadhanaScoreMonths: 3,
        },
        {
          levelName: 'Sevak',
          levelOrder: 3,
          chantingRoundsRequired: 4,
          chantingMonths: 3,
          morningProgram: 'none',
          spReadingPagesPerMonth: 30,
          booksToRead: 'PQPA',
          courseSyllabus: 'GTG',
          classFreqPerMonth: 2,
          oneOnOnePerMonth: 1,
          acceptKrishnaSpg: 'YES',
          serviceHoursMonth: 4,
          donationRequired: 'none',
          avoidOnionGarlic: 'unhappy',
          avoidIntoxicants: 'unhappy',
          noGambling: false,
          noIllicitSex: false,
          avoidNonveg: false,
          fasting: 'trying',
          kanthiMala: false,
          sadhanaScoreRequired: '75',
          sadhanaScoreMonths: 3,
        },
        {
          levelName: 'Sadhaka',
          levelOrder: 4,
          chantingRoundsRequired: 8,
          chantingMonths: 3,
          morningProgram: 'try',
          spReadingPagesPerMonth: 45,
          booksToRead: 'POY & RV',
          courseSyllabus: 'PBP',
          classFreqPerMonth: 2,
          oneOnOnePerMonth: 1,
          acceptKrishnaSpg: 'YES',
          serviceHoursMonth: 4,
          donationRequired: 'none',
          avoidOnionGarlic: 'mostly',
          avoidIntoxicants: 'mostly',
          noGambling: true,
          noIllicitSex: true,
          avoidNonveg: true,
          fasting: 'ekadashi',
          kanthiMala: false,
          sadhanaScoreRequired: '75',
          sadhanaScoreMonths: 3,
        },
        {
          levelName: 'Upasaka',
          levelOrder: 5,
          chantingRoundsRequired: 12,
          chantingMonths: 3,
          morningProgram: 'daily',
          spReadingPagesPerMonth: 45,
          booksToRead: 'SSR',
          courseSyllabus: 'SE',
          classFreqPerMonth: 3,
          oneOnOnePerMonth: 1,
          acceptKrishnaSpg: 'YES',
          serviceHoursMonth: 6,
          donationRequired: 'try',
          avoidOnionGarlic: 'mostly',
          avoidIntoxicants: 'mostly',
          noGambling: true,
          noIllicitSex: true,
          avoidNonveg: true,
          fasting: 'ekadashi',
          kanthiMala: false,
          sadhanaScoreRequired: '75',
          sadhanaScoreMonths: 3,
        },
        {
          levelName: 'Caranashraya',
          levelOrder: 6,
          chantingRoundsRequired: 16,
          chantingMonths: 3,
          morningProgram: 'daily',
          spReadingPagesPerMonth: 45,
          booksToRead: 'BG Intro-Ch9',
          courseSyllabus: 'BH',
          classFreqPerMonth: 3,
          oneOnOnePerMonth: 1,
          acceptKrishnaSpg: 'YES',
          serviceHoursMonth: 6,
          donationRequired: 'yes',
          avoidOnionGarlic: 'fully',
          avoidIntoxicants: 'yes',
          noGambling: true,
          noIllicitSex: true,
          avoidNonveg: true,
          fasting: 'ekadashi',
          kanthiMala: true,
        },
        {
          levelName: 'Harinam Diksha',
          levelOrder: 7,
          chantingRoundsRequired: 16,
          chantingMonths: 6,
          morningProgram: 'daily',
          spReadingPagesPerMonth: 45,
          booksToRead: 'BG Full',
          courseSyllabus: 'IDC',
          classFreqPerMonth: 3,
          oneOnOnePerMonth: 1,
          acceptKrishnaSpg: 'YES',
          serviceHoursMonth: 6,
          donationRequired: 'yes',
          avoidOnionGarlic: 'fully',
          avoidIntoxicants: 'yes',
          noGambling: true,
          noIllicitSex: true,
          avoidNonveg: true,
          fasting: 'ekadashi',
          kanthiMala: true,
        },
      ],
    });

    // Seed Config (from PDF page 50)
    const configResult = await Config.bulkCreate({
      records: [
        {
          configKey: 'Next Ashray Exam',
          configValue: '4/10/2026',
        },
        {
          configKey: 'whatsapp_reminder',
          configValue: 'Hare Krishna {user_name}! Please fill your Sadhana report for today. It only takes a minute and helps track your spiritual progress. Regards, {guide_name}',
        },
      ],
    });

    // Seed Services (from PDF pages 8-11)
    const servicesResult = await Services.bulkCreate({
      records: [
        {
          serviceName: 'Temple Hall Brooming & Mopping',
          timeSlot: '9:00 PM',
          sortOrder: 1,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Cleaning',
          requiredSkillsJson: '[]',
          description: 'Broom and mop the main temple hall',
          isActive: true,
          dueOffsetMinutes: 45,
          durationMinutes: 45,
        },
        {
          serviceName: 'Prasadam Hall Brooming & Mopping',
          timeSlot: '9:00 PM',
          sortOrder: 2,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Cleaning',
          requiredSkillsJson: '[]',
          description: 'Broom and mop the prasadam hall',
          isActive: true,
          dueOffsetMinutes: 45,
          durationMinutes: 45,
        },
        {
          serviceName: 'TH Furniture Cleaning (MMD)',
          timeSlot: '8:00 PM – 9:00 PM',
          sortOrder: 3,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Cleaning',
          requiredSkillsJson: '[]',
          description: 'Clean temple hall furniture',
          isActive: true,
          dueOffsetMinutes: 45,
          durationMinutes: 30,
        },
        {
          serviceName: 'Morning Pujari',
          timeSlot: '5:00 AM',
          sortOrder: 4,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Altar',
          requiredSkillsJson: '["pujari_trained"]',
          description: 'Morning puja — requires 2 trained pujaris',
          isActive: true,
          dueOffsetMinutes: 60,
          durationMinutes: 60,
        },
        {
          serviceName: 'Aarti Plate Cleaning',
          timeSlot: '8:00 AM – 9:00 PM',
          sortOrder: 5,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Altar',
          requiredSkillsJson: '[]',
          description: 'Clean aarti plates throughout the day',
          isActive: true,
          dueOffsetMinutes: 90,
          durationMinutes: 90,
        },
        {
          serviceName: 'Morning Prasadam Shifting',
          timeSlot: '7:40 AM',
          sortOrder: 6,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Prasadam',
          requiredSkillsJson: '[]',
          description: 'Shift morning prasadam to serving area',
          isActive: true,
          dueOffsetMinutes: 20,
          durationMinutes: 20,
        },
        {
          serviceName: 'Utensils Cleaning Morning',
          timeSlot: '8:00 AM – 2:00 PM',
          sortOrder: 7,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Cleaning',
          requiredSkillsJson: '[]',
          description: 'Clean kitchen utensils — morning shift',
          isActive: true,
          dueOffsetMinutes: 120,
          durationMinutes: 120,
        },
        {
          serviceName: 'Utensils Cleaning Evening',
          timeSlot: '7:00 PM – 10:00 PM',
          sortOrder: 8,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Cleaning',
          requiredSkillsJson: '[]',
          description: 'Clean kitchen utensils — evening shift',
          isActive: true,
          dueOffsetMinutes: 90,
          durationMinutes: 90,
        },
        {
          serviceName: 'Leftover Prasadam Management',
          timeSlot: '9:00 PM',
          sortOrder: 9,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Prasadam',
          requiredSkillsJson: '[]',
          description: 'Manage and store leftover prasadam properly',
          isActive: true,
          dueOffsetMinutes: 45,
          durationMinutes: 45,
        },
        {
          serviceName: 'Mangala Aarti Online Telecast & SB Class',
          timeSlot: '5:30 AM',
          sortOrder: 10,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Tech',
          requiredSkillsJson: '["audio_visual"]',
          description: 'Telecast Mangala Aarti online & arrange SB class',
          isActive: true,
          dueOffsetMinutes: 45,
          durationMinutes: 45,
        },
        {
          serviceName: 'Water Pots Cleaning & Filling (GF & FF)',
          timeSlot: 'Morning',
          sortOrder: 11,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Cleaning',
          requiredSkillsJson: '[]',
          description: 'Clean and fill water pots on ground floor & first floor',
          isActive: true,
          dueOffsetMinutes: 60,
          durationMinutes: 30,
        },
        {
          serviceName: 'Altar Opening & Evening Prasadam Offering',
          timeSlot: '4:00 PM',
          sortOrder: 12,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Altar',
          requiredSkillsJson: '["pujari_trained"]',
          description: 'Open altar and offer evening prasadam',
          isActive: true,
          dueOffsetMinutes: 30,
          durationMinutes: 30,
        },
        {
          serviceName: 'Evening PH & Table Cleaning & Prasadam Shifting',
          timeSlot: '4:45 PM',
          sortOrder: 13,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Prasadam',
          requiredSkillsJson: '[]',
          description: 'Clean prasadam hall tables and shift prasadam',
          isActive: true,
          dueOffsetMinutes: 30,
          durationMinutes: 30,
        },
        {
          serviceName: 'Altar Cleaning & Closing (Evening)',
          timeSlot: '7:15 PM – 8:20 PM',
          sortOrder: 14,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Altar',
          requiredSkillsJson: '["pujari_trained"]',
          description: 'Clean and close altar for the evening',
          isActive: true,
          dueOffsetMinutes: 30,
          durationMinutes: 30,
        },
        {
          serviceName: 'Standby Pujari',
          timeSlot: 'On call',
          sortOrder: 15,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Altar',
          requiredSkillsJson: '["pujari_trained"]',
          description: 'On-call backup pujari for the day',
          isActive: true,
          dueOffsetMinutes: 60,
          durationMinutes: 60,
        },
        {
          serviceName: 'Clothes Folding Seva',
          timeSlot: 'Flexible',
          sortOrder: 16,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Other',
          requiredSkillsJson: '[]',
          description: 'Fold and arrange devotee clothes',
          isActive: true,
          dueOffsetMinutes: 120,
          durationMinutes: 60,
        },
        {
          serviceName: 'Prasadam Serving',
          timeSlot: 'Meal times',
          sortOrder: 17,
          peopleNeeded: 2,
          serviceScope: 'General',
          category: 'Prasadam',
          requiredSkillsJson: '[]',
          description: 'Serve prasadam during meal times',
          isActive: true,
          dueOffsetMinutes: 30,
          durationMinutes: 30,
        },
        {
          serviceName: 'Afternoon Altar Closing',
          timeSlot: '12:30 PM',
          sortOrder: 18,
          peopleNeeded: 1,
          serviceScope: 'General',
          category: 'Altar',
          requiredSkillsJson: '["pujari_trained"]',
          description: 'Close the altar after afternoon program',
          isActive: true,
          dueOffsetMinutes: 20,
          durationMinutes: 30,
        },
      ],
    });

    return {
      deletedLevels: existingLevels.records.length,
      deletedConfig: existingConfig.records.length,
      deletedServices: existingServices.records.length,
      deletedChecklists: existingChecklists.records.length,
      levelsCreated: levelsResult.records.length,
      configCreated: configResult.records.length,
      servicesCreated: servicesResult.records.length,
      status: 'All real data seeded successfully!',
    };
  },
});
